name: TeachersToday-Action

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ttadmin/PROJECTS/teachers-today-backend
            git status
            git pull origin main

            pnpm i
            pm2 restart backend
            echo "Hi from server"
